pipeline {
    agent any
    environment {
        NAMESPACE = "group1-team8"
    }
    stages {
        stage('Deploy and Service to Kubernetes') {
            steps {
                script {
                    try {sh "kubectl delete -f ./prometheus/prometheus-deploy.yaml -n ${NAMESPACE}"} catch (e) {catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE'){ sh "exit 0"}}
                    try {sh "kubectl delete -f ./prometheus/prometheus-service.yaml -n ${NAMESPACE}"} catch (e) {catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE'){ sh "exit 0"}}
                    try {sh "kubectl delete -f ./prometheus/prometheus-config.yaml -n ${NAMESPACE}"} catch (e) {catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE'){ sh "exit 0"}}
                    try {sh "kubectl apply -f ./prometheus/prometheus-config.yaml -n ${NAMESPACE}"} catch (e) {catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE'){ sh "exit 0"}}
                    try {sh "kubectl apply -f ./prometheus/prometheus-deploy.yaml -n ${NAMESPACE}"} catch (e) {catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE'){ sh "exit 0"}}
                    try {sh "kubectl apply -f ./prometheus/prometheus-service.yaml -n ${NAMESPACE}"} catch (e) {catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE'){ sh "exit 0"}}
                }
            }
        }
    }
}
