pipeline {
    agent any
    environment {
        REGISTRY = "k8s-vga-worker1:5000"
        IMAGE_NAME = "team8-gatewayserver"
        IMAGE_TAG = "latest"
        NAMESPACE = "group1-team8"
        JAVA_HOME = "/tmp/jdk-21.0.5"
        PATH = "${JAVA_HOME}/bin:${PATH}"
    }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/seo-dk/work.git'
            }
        }
        stage('Build with Gradle') {
            steps {
                script {
                    sh 'cd gatewayserver && mvn clean package -DskipTests'
                }
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    sh "docker build -t ${REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG} ./gatewayserver"
                }
            }
        }
        stage('Push Docker Image') {
            steps {
                script {
                    sh "docker push ${REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}"
                }
            }
        }
        stage('Deploy and Service to Kubernetes') {
            steps {
                script {
                    try {sh "kubectl delete -f ./gatewayserver/gatewayserver-deploy.yaml -n ${NAMESPACE}"} catch (e) {catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE'){ sh "exit 0"}}
                    try {sh "kubectl delete -f ./gatewayserver/gatewayserver-service.yaml -n ${NAMESPACE}"} catch (e) {catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE'){ sh "exit 0"}}
                    try {sh "kubectl apply -f ./gatewayserver/gatewayserver-deploy.yaml -n ${NAMESPACE}"} catch (e) {catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE'){ sh "exit 0"}}
                    try {sh "kubectl apply -f ./gatewayserver/gatewayserver-service.yaml -n ${NAMESPACE}"} catch (e) {catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE'){ sh "exit 0"}}
                }
            }
        }
        // stage('Deployment Image to Update') {
        //     steps {
        //         script {
        //             sh "kubectl set image deployment/team8-accounts team8-accounts=${REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG} --namespace=${NAMESPACE}"
        //             sh "kubectl rollout restart deployment team8-accounts -n ${NAMESPACE}"
        //         }
        //     }
        // }
    }
}
