# Team8 Accounts 서비스에 대한 개별 설정
server:
  port: 9020  # Accounts 서비스의 기본 포트

spring:
  application:
    name: team8-accounts  # 서비스 이름 정의

  datasource:
    url: jdbc:h2:mem:testdb  # H2 인메모리 데이터베이스 사용
    driverClassName: org.h2.Driver
    username: sa
    password: ''

  h2:
    console:
      enabled: true  # H2 콘솔 활성화

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true  # SQL 쿼리 출력 활성화

eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    prefer-ip-address: true

  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 10
    service-url:
      # defaultZone: http://localhost:8761/eureka/
      defaultZone: http://team8-eureka:80/eureka/

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 100 # 요청 수
      permittedNumberOfCallsInHalfOpenState: 2 # half-open 상태에서 허용되는 요청 수
      failureRateThreshold: 50 # 실패율 50% 이상이면 open
      waitDurationInOpenState: 10000 # open 상태 지속 시간
      
    instances:  
      accountServiceFallback:
        baseConfig: default
        slowCallRateThreshold: 50  # 50% 이상 느린 응답 시 OPEN
        slowCallDurationThreshold: 2000  # 2초 이상 걸리면 slow call로 판단
        minimumNumberOfCalls: 4    # 최소 4개의 요청이 있어야 통계 계산 시작
        slidingWindowSize: 6       # 최근 6개의 요청 기준으로 실패율 계산
        
#  rabbitmq:
#    host: 192.168.100.221    # RabbitMQ 서버 주소
#    port: 30880              # 기본 포트
#    username: guest         # RabbitMQ 사용자 이름
#    password: guest         # RabbitMQ 비밀번호
#    virtual-host: /         # 기본 가상 호스트 (옵션)
#    template:
#      exchange: account-service-exchange   # Exchange 이름
#      routing-key: account-service-routing-key  # Routing key
#    listener:
#      simple:
#        concurrency: 3      # 소비자 수
#        max-concurrency: 10 # 최대 소비자 수
