
pipeline {
    agent any
    environment {
        REGISTRY = "k8s-vga-worker1:5000"
        NAMESPACE = "group1-team8"
        JAVA_HOME = "/tmp/jdk-21.0.5"
        PATH = "${JAVA_HOME}/bin:${PATH}"
    }
    stages {
        stage('Deploy and Service to Kubernetes') {
            steps {
                script {
                    sh "kubectl apply -f ./mysql/mysql-deploy.yaml -n ${NAMESPACE}"
                    sh "kubectl apply -f ./mysql/mysql-service.yaml -n ${NAMESPACE}"
                }
            }
        }
    }
}
