pipeline {
    agent any
    environment {
        REGISTRY = "k8s-vga-worker1:5000"
        IMAGE_NAME = "team8-demo"
        IMAGE_TAG = "latest"
        NAMESPACE = "group1-team8"
        JAVA_HOME = "/tmp/jdk-21.0.5"
        PATH = "${JAVA_HOME}/bin:${PATH}"
    }
    stages {
        stage('Checkout') {
            steps {
                // Git 저장소에서 소스 코드 체크아웃 (branch 지정 : 본인 repository의 branch 이름으로 설정)
                git branch: 'main', url: 'https://github.com/seo-dk/work.git'
            }
        }
        stage('Build with Gradle') {
            steps {
                script {
                    sh 'cd demo && mvn clean package -DskipTests'
                }
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    sh "docker build -t ${REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG} ./demo"
                }
            }
        }
        stage('Push Docker Image') {
            steps {
                script {
                    // Docker 이미지를 Registry Server에 푸시
                    sh "docker push ${REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}"
                }
            }
        }
        stage('Deploy and Service to Kubernetes') {
            steps {
                script {
                    // Kubernetes Deployment and Service 생성 및 적용 (1일차 교육때 사용한 deploy & service 생성 yaml 파일 등록하여 사용)
                    sh "kubectl delete -f ./demo/demo-deploy.yaml -n ${NAMESPACE}"
                    sh "kubectl apply -f ./demo/demo-deploy.yaml -n ${NAMESPACE}"
                    sh "kubectl delete -f ./demo/demo-service.yaml -n ${NAMESPACE}"
                    sh "kubectl apply -f ./demo/demo-service.yaml -n ${NAMESPACE}"
                }
            }
        }        
        // stage('Deployment Image to Update') {
        //     steps {
        //         script {
        //             // Kubenetes에서 특정 Deployment의 컨테이너 이미지를 업데이트 (아래 이름은 중복되지 않게 주의하여 지정, deployment, selector 이름으로)
        //             sh "kubectl set image deployment/team8-demo team8-demo=${REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG} --namespace=${NAMESPACE}"
        //             sh "kubectl rollout restart deployment team8-demo -n ${NAMESPACE}"
        //         }
        //     }
        // }
    }
}
