pipeline {
    agent any
    parameters {
        booleanParam(
            defaultValue: true,
            name: 'APPLY_FLAG'
        )
    }
    environment {
        NAMESPACE = "group1-team8"
    }
    stages {
        stage('apply or delete (Deploy / Service)') {
            steps {
                script {
                    if ("${APPLY_FLAG}" == "true") {
                        sh "echo apply excute"
                        try {sh "kubectl apply -f ./configserver/configserver-deploy.yaml -n ${NAMESPACE}"} catch (e) {catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE'){ sh "exit 0"}}                        
                        try {sh "kubectl apply -f ./yaeureka/eureka-deploy.yaml -n ${NAMESPACE}"} catch (e) {catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE'){ sh "exit 0"}}                        
                        try {sh "kubectl apply -f ./gatewayserver/gatewayserver-deploy.yaml -n ${NAMESPACE}"} catch (e) {catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE'){ sh "exit 0"}}                        
                        try {sh "kubectl apply -f ./accounts/accounts-deploy.yaml -n ${NAMESPACE}"} catch (e) {catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE'){ sh "exit 0"}}                        
                        try {sh "kubectl apply -f ./loans/loans-deploy.yaml -n ${NAMESPACE}"} catch (e) {catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE'){ sh "exit 0"}}                      
                        try {sh "kubectl apply -f ./cards/cards-deploy.yaml -n ${NAMESPACE}"} catch (e) {catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE'){ sh "exit 0"}}
                        try {sh "kubectl apply -f ./rabbitmq/rabbitmq-deploy.yaml -n ${NAMESPACE}"} catch (e) {catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE'){ sh "exit 0"}}
                        try {sh "kubectl apply -f ./mysql/mysql-deploy.yaml -n ${NAMESPACE}"} catch (e) {catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE'){ sh "exit 0"}}
                        try {sh "kubectl apply -f ./demo/demo-deploy.yaml -n ${NAMESPACE}"} catch (e) {catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE'){ sh "exit 0"}}
                        try {sh "kubectl apply -f ./dummy/dummy-deploy.yaml -n ${NAMESPACE}"} catch (e) {catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE'){ sh "exit 0"}}
                        try {sh "kubectl apply -f ./sample/sample-deploy.yaml -n ${NAMESPACE}"} catch (e) {catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE'){ sh "exit 0"}}
                        try {sh "kubectl apply -f ./prometheus/prometheus-deploy.yaml -n ${NAMESPACE}"} catch (e) {catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE'){ sh "exit 0"}}
                        try {sh "kubectl apply -f ./zipkin/zipkin-deploy.yaml -n ${NAMESPACE}"} catch (e) {catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE'){ sh "exit 0"}}
                        try {sh "kubectl apply -f ./jaeger/jaeger-deploy.yaml -n ${NAMESPACE}"} catch (e) {catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE'){ sh "exit 0"}}
                        try {sh "kubectl apply -f ./grafana/grafana-deploy.yaml -n ${NAMESPACE}"} catch (e) {catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE'){ sh "exit 0"}}
                    } else{
                        sh "echo delete excute"
                        try {sh "kubectl delete -f ./configserver/configserver-deploy.yaml -n ${NAMESPACE}"} catch (e) {catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE'){ sh "exit 0"}}                        
                        try {sh "kubectl delete -f ./yaeureka/eureka-deploy.yaml -n ${NAMESPACE}"} catch (e) {catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE'){ sh "exit 0"}}                        
                        try {sh "kubectl delete -f ./gatewayserver/gatewayserver-deploy.yaml -n ${NAMESPACE}"} catch (e) {catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE'){ sh "exit 0"}}                        
                        try {sh "kubectl delete -f ./accounts/accounts-deploy.yaml -n ${NAMESPACE}"} catch (e) {catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE'){ sh "exit 0"}}                        
                        try {sh "kubectl delete -f ./loans/loans-deploy.yaml -n ${NAMESPACE}"} catch (e) {catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE'){ sh "exit 0"}}                      
                        try {sh "kubectl delete -f ./cards/cards-deploy.yaml -n ${NAMESPACE}"} catch (e) {catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE'){ sh "exit 0"}}
                        try {sh "kubectl delete -f ./rabbitmq/rabbitmq-deploy.yaml -n ${NAMESPACE}"} catch (e) {catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE'){ sh "exit 0"}}
                        try {sh "kubectl delete -f ./mysql/mysql-deploy.yaml -n ${NAMESPACE}"} catch (e) {catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE'){ sh "exit 0"}}
                        try {sh "kubectl delete -f ./demo/demo-deploy.yaml -n ${NAMESPACE}"} catch (e) {catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE'){ sh "exit 0"}}
                        try {sh "kubectl delete -f ./dummy/dummy-deploy.yaml -n ${NAMESPACE}"} catch (e) {catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE'){ sh "exit 0"}}
                        try {sh "kubectl delete -f ./sample/sample-deploy.yaml -n ${NAMESPACE}"} catch (e) {catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE'){ sh "exit 0"}}
                        try {sh "kubectl delete -f ./prometheus/prometheus-deploy.yaml -n ${NAMESPACE}"} catch (e) {catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE'){ sh "exit 0"}}
                        try {sh "kubectl delete -f ./zipkin/zipkin-deploy.yaml -n ${NAMESPACE}"} catch (e) {catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE'){ sh "exit 0"}}
                        try {sh "kubectl delete -f ./jaeger/jaeger-deploy.yaml -n ${NAMESPACE}"} catch (e) {catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE'){ sh "exit 0"}}
                        try {sh "kubectl delete -f ./grafana/grafana-deploy.yaml -n ${NAMESPACE}"} catch (e) {catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE'){ sh "exit 0"}}
                    }
                }
            }
        }
    }
}
