pipeline {
    agent any
    parameters {
        defaultValue: true,
        name: 'APPLY_FLAG'
    }
    environment {
        NAMESPACE = "group1-team8"
    }
    stages {
        stage('apply or delete (Deploy / Service)') {
            steps {
                script {
                    if (${APPLY_FLAG} == true) {
                        sh "kubectl apply -f ./yamls/configserver-deploy.yaml -n ${NAMESPACE}"
                        sh "kubectl apply -f ./yamls/configserver-service.yaml -n ${NAMESPACE}"
                        sh "kubectl apply -f ./yamls/eureka-deploy.yaml -n ${NAMESPACE}"
                        sh "kubectl apply -f ./yamls/eureka-service.yaml -n ${NAMESPACE}"
                        sh "kubectl apply -f ./yamls/gatewayserver-deploy.yaml -n ${NAMESPACE}"
                        sh "kubectl apply -f ./yamls/gatewayserver-service.yaml -n ${NAMESPACE}"
                        sh "kubectl apply -f ./yamls/accounts-deploy.yaml -n ${NAMESPACE}"
                        sh "kubectl apply -f ./yamls/accounts-service.yaml -n ${NAMESPACE}"
                        sh "kubectl apply -f ./yamls/loans-deploy.yaml -n ${NAMESPACE}"
                        sh "kubectl apply -f ./yamls/loans-service.yaml -n ${NAMESPACE}"
                        sh "kubectl apply -f ./yamls/cards-deploy.yaml -n ${NAMESPACE}"
                        sh "kubectl apply -f ./yamls/cards-service.yaml -n ${NAMESPACE}"
                        sh "kubectl apply -f ./yamls/rabbitmq-deploy.yaml -n ${NAMESPACE}"
                        sh "kubectl apply -f ./yamls/rabbitmq-service.yaml -n ${NAMESPACE}"
                        sh "kubectl apply -f ./yamls/demo-deploy.yaml -n ${NAMESPACE}"
                        sh "kubectl apply -f ./yamls/demo-service.yaml -n ${NAMESPACE}"
                        sh "kubectl apply -f ./yamls/mysql-deploy.yaml -n ${NAMESPACE}"
                        sh "kubectl apply -f ./yamls/mysql-service.yaml -n ${NAMESPACE}"
                    } else{
                        sh "kubectl delete -f ./yamls/mysql-service.yaml -n ${NAMESPACE}"
                        sh "kubectl delete -f ./yamls/mysql-deploy.yaml -n ${NAMESPACE}"
                        sh "kubectl delete -f ./yamls/demo-service.yaml -n ${NAMESPACE}"
                        sh "kubectl delete -f ./yamls/demo-deploy.yaml -n ${NAMESPACE}"
                        sh "kubectl delete -f ./yamls/rabbitmq-service.yaml -n ${NAMESPACE}"
                        sh "kubectl delete -f ./yamls/rabbitmq-deploy.yaml -n ${NAMESPACE}"
                        sh "kubectl delete -f ./yamls/cards-service.yaml -n ${NAMESPACE}"
                        sh "kubectl delete -f ./yamls/cards-deploy.yaml -n ${NAMESPACE}"
                        sh "kubectl delete -f ./yamls/loans-service.yaml -n ${NAMESPACE}"
                        sh "kubectl delete -f ./yamls/loans-deploy.yaml -n ${NAMESPACE}"
                        sh "kubectl delete -f ./yamls/accounts-service.yaml -n ${NAMESPACE}"
                        sh "kubectl delete -f ./yamls/accounts-deploy.yaml -n ${NAMESPACE}"
                        sh "kubectl delete -f ./yamls/gatewayserver-service.yaml -n ${NAMESPACE}"
                        sh "kubectl delete -f ./yamls/gatewayserver-deploy.yaml -n ${NAMESPACE}"
                        sh "kubectl delete -f ./yamls/eureka-service.yaml -n ${NAMESPACE}"
                        sh "kubectl delete -f ./yamls/eureka-deploy.yaml -n ${NAMESPACE}"
                        sh "kubectl delete -f ./yamls/configserver-service.yaml -n ${NAMESPACE}"
                        sh "kubectl delete -f ./yamls/configserver-deploy.yaml -n ${NAMESPACE}"
                    }
                }
            }
        }
    }
}
