FROM jenkins/jenkins:lts
USER root
RUN apt-get update && apt-get install -y \
    curl \
    unzip \
    git \
    docker.io && \
    rm -rf /var/lib/apt/lists/*

RUN curl -fsSL https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.6%2B7/OpenJDK21U-jdk_x64_linux_hotspot_21.0.6_7.tar.gz \
    | tar -xz -C /opt && \
    ln -s /opt/jdk-21.0.6+7/bin/java /usr/bin/java

ENV MAVEN_VERSION=3.9.6
ENV JAVA_HOME=/opt/jdk-21.0.6+7/
ENV PATH="${JAVA_HOME}/bin:${PATH}"

RUN curl -fsSL https://downloads.apache.org/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz \
    | tar -xz -C /opt && \
    ln -s /opt/apache-maven-${MAVEN_VERSION}/bin/mvn /usr/bin/mvn

RUN usermod -aG docker jenkins

USER jenkins

RUN java -version && mvn -version